import turtle
from turtle import Screen

s=Screen()
s.bgcolor("white")

a=turtle.Turtle()
a.shape("arrow")
a.pensize(7)
a.color("blue")

a.begin_fill()
a.circle(140,360)
a.end_fill()
a.right(7)
a.backward(32)
a.color('white')
a.pensize(3)
a.begin_fill()
a.left(97)
a.forward(98)
a.left(90)
a.forward(40)
a.right(90)
a.forward(40)
a.right(90)
a.forward(40)
a.left(90)
a.forward(34)
a.circle(-45,90)
a.forward(40)
a.right(90)
a.forward(40)
a.right(90)
a.forward(20)
a.circle(17,90)
a.forward(23)
a.left(90)
a.forward(40)
a.right(90)
a.forward(40)
a.right(90)
a.forward(40)
a.left(90)
a.forward(108)
a.right(90)
a.forward(48)
a.right(90)
a.forward(8)
a.end_fill()
a.hideturtle()
turtle.done()
turtle.mainloop()
